### ISSUE TITLE
[bug] Attempting to connect to WalletConnect leads to "Buffer is not defined" 

### ISSUE THREAD

**Issue by joshrutkowski** [tmm/wagmi#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.21

### Current Behavior

When I try to connect to Wallet Connect, it throws the following error and does not display QR code:

```
ReferenceError: Buffer is not defined
    at typedarrayToBuffer (index.js:15:1)
    at Module.arrayToBuffer (index.js:28:1)
    at Module.generateKey (index.js:7:1)
    at WalletConnect._generateKey (index.js:847:1)
    at WalletConnect.createSession (index.js:299:1)
    at SignerConnection.create (index.js:136:1)
    at index.js:54:1
    at new Promise (<anonymous>)
    at SignerConnection.open (index.js:47:1)
    at JsonRpcProvider.open (provider.js:84:1)
```

### Expected Behavior

To be able to connect using Wallet Connect

### Steps To Reproduce

1. Using RedwoodJS
2. Follow [Getting Started](https://wagmi.sh/getting-started) guide
3. Click Wallet Connect button
4. See error message: `Buffer is not defined`
5. QR code does not pop up

### Anything else?

Related: #261 

Related: https://github.com/WalletConnect/walletconnect-monorepo/issues/748

**Comment by joshrutkowski** [comment]
Got it working.

Added buffer
`yarn add buffer` [6.0.3](https://www.npmjs.com/package/buffer#usage)

Updated connectors:

```
import { chain, defaultChains } from "wagmi";
import { InjectedConnector } from "wagmi/connectors/injected";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";
import { WalletLinkConnector } from "wagmi/connectors/walletLink";
import { Buffer } from "buffer";

// polyfill Buffer for client
if (!window.Buffer) {
  window.Buffer = Buffer;
}

// Chains for connectors to support
const chains = defaultChains;

// API key for Ethereum node
// Two popular services are Infura (infura.io) and Alchemy (alchemy.com)
const infuraId = process.env.INFURA_ID;

// Set up connectors
const connectors = ({ chainId }) => {
  const rpcUrl =
    defaultChains.find((x) => x.id === chainId)?.rpcUrls?.[0] ??
    chain.mainnet.rpcUrls[0];
  return [
    new WalletLinkConnector({
      options: {
        appName: "app name",
        jsonRpcUrl: `${rpcUrl}/${infuraId}`,
      },
    }),
    new WalletConnectConnector({
      chains: defaultChains,
      options: {
        infuraId: "Your infura id",
        qrcode: true,
      },
    }),
    new InjectedConnector({
      chains,
      options: { shimDisconnect: true },
    }),
  ];
};

export { connectors, Buffer };
```

**Comment by kiliman** [comment]
I'm glad you got it working. I realized after I posted that you weren't using Remix. But I figured the general idea (importing `buffer` polyfill) would still apply.
