### ISSUE TITLE
[bug] Alchemy RPC request seems to be coming from the server and not the client Remix exmaple

### ISSUE THREAD

**Issue by epitaphmike** [tmm/wagmi#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.5

### Current Behavior

I am trying to whitelist the domain for the alchemy key but it seems the referrer is the server not the client. I checked with alchemy support and they gave me a list of IP addresses that were of my server location. Any ideas? I have implemented the WAGMI client as per the documentation.

### Expected Behavior

referrer is of the client so the domain can be whitelisted protecting the alchemy API key

### Steps To Reproduce

1. Implement Remix Example
2. white list a domain on Alchemy 
3. Breaks app

**Comment by tmm** [comment]
Does everything work as expected without the allowlist? Can you provide a minimal reproducible example and re-open this issue?

**Comment by epitaphmike** [comment]
This is the main error from my fly.io server. In the docker container. I am not sure the best way to provide a reproducible example, but the app works as expected without the allowlist

```2022-06-18T16:52:17.425 app[f5fa4c4b] iad [info] GET /healthcheck 200 - - 73.572 ms

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] /myapp/node_modules/@ethersproject/logger/src.ts/index.ts:261

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] const error: any = new Error(message);

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] ^

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.4)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at Logger.makeError (/myapp/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at Logger.throwError (/myapp/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at AlchemyWebSocketProvider.<anonymous> (/myapp/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:431:23)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at step (/myapp/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at Object.throw (/myapp/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at rejected (/myapp/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)

2022-06-18T16:52:17.559 app[f5fa4c4b] iad [info] at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by soccerarenadev** [comment]
I've having today the same issue. I didn't have this error before.

![telegram-cloud-photo-size-4-5952061551513024950-y](https://user-images.githubusercontent.com/99416733/197271515-3625f50c-5b5f-41ad-ae39-98776db663e1.jpg)

**Comment by Hussainzz** [comment]
![Screenshot 2022-10-22 at 9 38 02 AM](https://user-images.githubusercontent.com/13753141/197318416-d3a3c72b-4bb8-4ca6-a276-2ae6ec6c443d.png)

```
const { chains, provider, webSocketProvider } = configureChains(
  [chain.polygonMumbai],
  [
    alchemyProvider({ apiKey: process.env.REACT_ALCHEMY_API_KEY }),
  ]
);

// Set up client
const client = createClient({
  autoConnect: true,
  connectors: [new MetaMaskConnector({ chains })],
  provider,
  webSocketProvider,
});

```

I am getting this error, i also tried adding new keys from alchemy same issue. Am i doing something wrong here ?

**Comment by owade** [comment]
I am getting Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.1) too. I have set my own achemy api key but its ignored
![wagmerror](https://user-images.githubusercontent.com/7558116/197327421-c5ab03b4-5771-4631-bdc2-1141d0241f29.png)
