### ISSUE TITLE
[bug] Invalid hook call originating from WagmiConfig

### ISSUE THREAD

**Issue by davidlee1435** [tmm/wagmi#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

On wagmi 0.4.12, I see the following stack trace in the Chrome console:

```
react.development.js:207 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:207
react.development.js:1632 Uncaught TypeError: Cannot read properties of null (reading 'useEffect')
    at Object.useEffect (react.development.js:1632:1)
    at WagmiConfig (wagmi.esm.js:224:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
react-dom.development.js:18687 The above error occurred in the <WagmiConfig> component:

    at WagmiConfig (http://localhost:3000/static/js/bundle.js:509520:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:611776:43)
    at ThemeSwitcherProvider (http://localhost:3000/static/js/bundle.js:639753:23)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:700376:19)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

I currently am working in a yarn workspace with two React apps. Both share the same wagmi version (0.4.12), but the other does not show this error.

**Comment by tmm** [comment]
Can you provide a minimal reproducible example and re-open? Will be faster to figure out what is happening and help you out.
